pouchcontainer/pouchrobot

server/reporter/weekly.go
we received some feedback that weekly report should be improved since some typo exist.
=> fix: update document of weekly report

server/reporter/reporter.go
=> feature: change weekly report time into Thursday

server/processor/issueProcessor/labeled.go, server/utils/matches.go, server/utils/utils.go
=> feature: remove P0 and make P1 highest priority

server/utils/matches.go
Signed-off-by: Eric Li <lcy041536@gmail.com>
feature: add shaloucy as maintainer
=> feature: add shaloucy as maintainer

server/gh/pulls.go, server/reporter/reviews.go, server/reporter/weekly.go
=> feature: add pull request reviews in weekly report of pouchrobot

server/fetcher/check_gap.go, server/fetcher/fetcher.go, server/server.go, server/utils/utils.go
Signed-off-by: Zou Rui <21751189@zju.edu.cn>
=> feature: add gap comment and label when pr is over 10 commits behind

Dockerfile, fetcher/check_gap.go, server.go
Signed-off-by: Zou Rui <21751189@zju.edu.cn>
=> fix stuck problem when detecting gaps

Dockerfile, fetcher/check_gap.go, server.go
Reverts pouchcontainer/pouchrobot#31
=> Revert "fix stuck problem when detecting gaps"

gh/repos.go, reporter/weekly.go
=> feature: add contributor number in weekly report

reporter/weekly.go
=> refactor: split code block in weekly report to make it clear

Dockerfile, fetcher/check_gap.go
Signed-off-by: Zou Rui <21751189@zju.edu.cn>
=> fix: check gap stuck

Dockerfile, fetcher/check_gap.go
Reverts pouchcontainer/pouchrobot#44
=> Revert "fix: check gap stuck"

config/config.go, fetcher/check_gap.go, fetcher/fetcher.go, main.go, server.go
=> feature: make gap commits configurable

docgenerator/api.go, docgenerator/cli.go, docgenerator/generator.go, gh/issue_comment.go, main.go, processor/processor.go, reporter/reporter.go, server.go, vendor/vendor.json
=> bugfix: make doc generator work fine

main.go
=> bugfix: fix flag naming of commits-gap

docgenerator/generator.go
=> bugfix: fix fmt %s to %d

docgenerator/generator.go, reporter/reporter.go
=> fix: change publish time of weekreport and doc generator

.circleci/config.yml, utils/slice.go, utils/slice_test.go
add CI support for pouchrobot
add some of utils.go
none
none
=> feature: add CI support for pouchrobot

CONTRIBUTING.md, README.md, fetcher/check_conflict.go, reporter/reporter.go
=> docs: fix ci failure via markdownlint and mispell

Dockerfile-Dragonfly
=> docs: add dockerfile specific for Dragonfly

config/config.go, main.go, reporter/reporter.go, server.go
feature: make week report time configurable
=> feature: make week report time configurable

config/config.go, docgenerator/api.go, docgenerator/cli.go, docgenerator/contributors.go, docgenerator/generator.go, main.go, server.go
=> refactor: make doc generation more configurable

docgenerator/generator.go, server.go
=> feature: make doc generation repo configurable

reporter/reporter.go, reporter/weekly_report.go
make repo's status change correct
It used to be the following with zero-value in it.
| Watch | Star | Fork | Contributors | New Issues | Closed Issues |
|:-----:|:----:|:----:|:------------:|:----------:|:-------------:|
|264 (↑0)|3424 (↑0)|834 (↑0)|93 (↑0)|0|0|
none
no need
none
none
=> bugfix: make repo's status change correct

processor/issueCommentProcessor/comment_created.go
support assign in commet to assign somebody
fixes https://github.com/alibaba/pouch/issues/2388
no need
none
none
=> feature: support assign in commet to assign somebody

fetcher/check_conflict.go, fetcher/check_gap.go
change loglevel from info to debug,
otherwise there are so many redundant logs there.
none
none
none
none
=> feature: change loglevel from info to debug

Dockerfile, Dockerfile-Dragonfly
=> docs: reorder Dockerfile to skip some build task

docgenerator/generator.go
=> linter: fix golinter issues

README.md, config/config.go, docgenerator/generator.go, main.go, server.go
It is much more convenient for user to setup doc generation time.
This pr tries to make doc generation time configurable.
none
none
none
none
=> feature: make doc generation time configurable

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, docgenerator/cli.go, docgenerator/contributors.go, docgenerator/generator.go
=> docs: make pouchrobot more general

config/config.go, gh/issues.go, main.go, processor/issueProcessor/issue_processor.go, processor/issueProcessor/opened.go, processor/processor.go, server.go, utils/translators/baidu_translation.go, utils/translators/translator.go
Signed-off-by: Frankzhaopku <syzhao1988@126.com>
fix typo
Signed-off-by: Frankzhaopku <syzhao1988@126.com>
fixes #84
=> Add issue auto translate function

reporter/weekly_report.go
This PR fix weekly report link of readme, link will generate from owner and repo.
=> fix weekly report readme link

utils/translators/baidu_translation.go, utils/utils.go
Signed-off-by: Frankzhaopku <syzhao1988@126.com>
Translation will skip the content without Chinese characters.
=> skip translation request without Chinese character

Dockerfile, Dockerfile-Dragonfly
Dockerfile: change building way of pouchrobot binary
no need
=> Dockerfile: change building way of pouchrobot binary

main.go
=> Output cfg

main.go
=> feature: output config value when daemon start

Dockerfile, Dockerfile-Dragonfly, server.go
=> distro: update golang version to 1.10.4

docgenerator/generator.go
=> log: add more descriptive log

docgenerator/generator.go
=> feature: do not remove current branch daily

Dockerfile, Dockerfile-Dragonfly
docs: update goversion to 1.12.6 in Dockerfile
Since after that, the pouchrobot could support go mod.
none
no need
none
none
=> docs: update goversion to 1.12.6 in Dockerfile
